config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
  get 'signup', to: 'users#new'
  resources :users, except: [:new]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 300}
end

app/models/user.rb
class User < ApplicationRecord
    before_save {self.email = email.downcase}
    has_many :articles
    validates :username, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 3, maximum: 25}
    VALID_EMAIL_REGEX = /\A[^@\s]+@([^@.\s]+\.)+[^@.\s]+\z/

    validates :email, presence: true, 
               uniqueness: {case_sensitive: false}, 
               length: {maximum: 60},
               format: { with: VALID_EMAIL_REGEX }
    has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(params.require(:article).permit(:title, :description, :image))
            flash[:notice] = "Article was updated successfully"
            redirect_to @article
        else
          render 'edit'
        end
    end

    def create
        @article = Article.new(params.require(:article).permit(:title, :description, :image))
        @article.user = User.first
        if @article.save
          flash[:notice] = "Article was created successfully"
          redirect_to @article
        else
          render 'new'
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy
        redirect_to articles_path
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
    end

    def about
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
      @user = User.new()
    end

    def show
      @user = User.find(params[:id])
    end

    def create
        @user = User.new(user_params)
        if @user.save
          flash[:notice] = "Welcome #{@user.username}, you have successfully signed up"
          redirect_to articles_path
        else
          render 'new'
        end
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = "Thanks #{@user.username}, you have successfully updated your account"
        redirect_to articles_path
      else
        render 'edit'
      end
    end

    private
    def user_params
        params.require(:user).permit(:username, :email, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<% if @article.errors.any? %>
  <h4>
      <% @article.errors.full_messages.each do |msg| %>
        <li style="color:red">
          <%= msg %>
        </li>
      <% end %>
  </h4>

<% end %>


<%= form_with(model: @article, data: { turbo: false }, local: true) do |f| %>

    <p>
      <%= f.label :title %>
      <br/>
      <%= f.text_field :title %>
    </p>

    <p>
      <%= f.label :description %>
      <br/>
      <%= f.text_area :description %>
    </p>

    <p>
      <%= f.file_field :image %>
    </p>

    <p>
      <%= f.submit %>
    </p>
    
<% end %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= render 'form' %>

<%= link_to 'Back to my article', articles_path %>

app/views/articles/index.html.erb
<h1>All my articles</h1>

<table class="table">
  <thead>
    <tr>
     <th scope="col">Title</th>
     <th scope="col">Description</th>
     <th scope="col">User</th>
     <th scope="col" colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.description %></td>
        <td><%= article.user.username %></td>
        <td><%= link_to 'Show', article_path(article), class: "btn btn-primary" %></td>
        <td><%= link_to 'Edit', edit_article_path(article), class: "btn btn-warning" %></td>
        <td><%= link_to 'Delete', article_path(article), data: { turbo_method: :delete }, class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Create a new article', new_article_path, class: "btn btn-dark" %>

app/views/articles/new.html.erb
<h1>Create a new article</h1>

<%= render 'form' %>

<%= link_to 'Back to my articles', articles_path %>

app/views/articles/show.html.erb
<h1>Showing article details</h1>
<% if @article.image.any? %>
    <%= image_tag(@article.image)%>
<% end %>
<p><strong>Title: </strong><%= @article.title %></p>
<p><strong>Description: </strong><%= @article.description%></p>
<p><strong>User: </strong><%= @article.user.username%></p>

<%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Delete', article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
<%= link_to 'Back to my articles', articles_path %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to 'ALPHA BLOG', root_path, class: "navbar-brand", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu">
            <li><%= link_to 'Articles', articles_path, class: "dropdown-item" %></li>
            <li><%= link_to 'Create a new article', new_article_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled">Disabled</a>
        </li>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
   
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <% flash.each do |name, msg| %>
      <li style="color:green">
        <%= msg %>
      </li>
    <% end %>  

    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h6>About</h6>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron">
        <h1 class="display-5 fw-bold">Ruby on Rails 7 project</h1>
        <p class="col-md-8 fs-4">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
        <%= link_to 'Sign up',signup_path, class: "btn btn-success btn-lg" %>
  </div>
</div>

<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <div class="col-md-4 d-flex align-items-center">
      <a href="/" class="mb-3 me-2 mb-md-0 text-muted text-decoration-none lh-1">
        <svg class="bi" width="30" height="24"><use xlink:href="#bootstrap"></use></svg>
      </a>
      <span class="mb-3 mb-md-0 text-muted">© 2022 Company, Inc</span>
    </div>
  </footer>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <h4 style="color:red">
  The following errors prevent the user to be created
      <% @user.errors.full_messages.each do |msg| %>
        <li style="color:red">
          <%= msg %>
        </li>
      <% end %>
  </h4>

<% end %>

<%= form_with(model: @user, data: { turbo: false }, local: true) do |f| %>

    <p>
      <%= f.label :username %>
      <br/>
      <%= f.text_field :username, placeholder: "Enter a username" %>
    </p>

    <p>
      <%= f.label :email %>
      <br/>
      <%= f.email_field :email, placeholder: "Example@example.com" %>
    </p>

    <% if not @user.password_digest? %>
      <p>
        <%= f.label :password %>
        <br/>
        <%= f.password_field :password, placeholder: "Enter your password" %>
      </p>
    <% end %>

    <p>
      <%= f.submit(@user.new_record? ? "Sign up" : "Update User") %>
    </p>
    
<% end %>

app/views/users/edit.html.erb
<h1>Edit your user info</h1>
<%= render 'form' %>

app/views/users/new.html.erb
<h1>Signup</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1>Showing User details</h1>
<p><strong>Username: </strong><%= @user.username %></p>
<p><strong>Description: </strong><%= @user.email%></p>

<% if @user.articles.any? %>
<h4>User articles</h4>
<% @user.articles.each do |usr|%>
    <p><strong><%= usr.title %></strong></p>
    <p><%= usr.description %></p>
<% end %>
<% end %>